version: '3.7'

services:
  app_node:
    container_name: nodeTS-app
    # command: 'npm run dev'
    command: /bin/sh -c "npm install --quiet  && npm install -D --quiet && npm run build && npm run dev"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/srv/src
    links:
      - 'db:mysql'
    depends_on:
      - db


  db:
    image: 'mysql:5.6'
    container_name: nodets-mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_USER=userdb'
      - 'MYSQL_PASSWORD=userpass'
    ports:
      - '3306:3306'
    volumes:
      - './DataBase/var/lib/mysql:/var/lib/mysql'
      - './DataBase/etc/mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d/'